config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/', to: 'static_pages#home'
  get '/gossip/new', to: 'gossips#new'
  post '/gossip/new', to: 'gossips#create'
  get '/gossip/:anonymous_author', to: 'gossips#show', as: 'gossip'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
    def new
        @gossip = Gossip.new
    end
    def create
        @gossip = Gossip.new
        @gossip.anonymous_author = params["anonym_auth"]
        @gossip.content = params["cont"]
        @gossip.save
        redirect_to gossip_path(@gossip.anonymous_author)
    end
    def show
        @gossip = Gossip.find_by_anonymous_author(params[:anonymous_author])
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def home
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/gossips/new.html.erb
<h1>Crée ton gossip</h1>

</br>

<form action='/gossip/new' method="POST">
    <p>Quel est ton gossip (ton anonymat sera conservé)</p>
    <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>" >
    <input type="text" name="anonym_auth">
    </br></br>
    <p>Qu'est-ce que tu as à nous raconter?</p>
    <input placeholder="écris ton ragot ici" type="textarea" name="cont">
    </br></br>
    <p>Oublies pas de valider</p>
    <input type="submit" name="Send">
</form>

app/views/gossips/show.html.erb
<h1> Bienvenue <%= @gossip.anonymous_author %> sur ta page </h1>
<br/><br/>

<h2> Ton dernier content </h2>

<p> <%= @gossip.content %> </p>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Accueil",   '#' %></li>
        <li><%= link_to "Index des gossips",   '#' %></li>
        <li><%= link_to "Nouveau gossip", '#' %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"/>
    <title>GossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Bienvenue !</h1>
  <h3>
    <%= link_to "Ici", '#' %> tu peux retrouver les moussaillons 🎓
  </h3>
  <%= link_to "Enregistre-toi !", gossip_new_path, class: "btn btn-lg btn-primary" %>
</div>